### ISSUE TITLE
Apache service doesn't start automatically

### ISSUE THREAD

**Issue by dagomar** [aegir-project/dockerfiles#39]
The first time I used the aegir project dockerfile using the recommended docker-compose setup everyting worked fine, but when I restarted I found that the apache service didn't start automatically. Manually starting apache from within the container worked fine for me. 

I'm not sure why this happens, I'm happy to provide more information if necessary.

**Comment by PaulLebmann** [comment]
Thanks for the hint, I ran into the same problem. I don't know why it happens, but to work around it I created a "start.sh" with

#!/bin/bash
sudo apache2ctl start
drush @hostmaster hosting-queued

, mounted it into the container and called it as command from my docker-compose.yml instead of just the command from the dockerfile (drush @hostmaster hosting-queued).

best regards

**Comment by PaulLebmann** [comment]
I think this is fixed with commit [aaa0ca380793c14f78dafca342664d55c6a403f2](https://github.com/aegir-project/dockerfiles/commit/aaa0ca380793c14f78dafca342664d55c6a403f2) since apache now is started in entrypoint.sh.
At least it works for me and the workaround described in the previous comment seems no longer to be necessary.

If other users have the same expierence I think this issue should be closed.

best regards!

**Comment by jonpugh** [comment]
Thanks @dagomar and @PaulLebmann for the report.

We were relying on the first hosting task to reload Apache for us, but in case of a docker restart, there are no tasks to run.

I added that commit yesterday to get Apache started as soon as possible.

Good luck!
